# Generated by Django 4.2.6 on 2023-12-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tictocDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
                ('winner', models.CharField(max_length=100)),
                ('terminal', models.CharField(max_length=100)),
                ('move', models.CharField(max_length=100)),
            ],
        ),
    ]
