# Generated by Django 4.2.6 on 2023-12-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictoc', '0002_rename_tictocdetail_tictocmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tictocmodel',
            name='action',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tictocmodel',
            name='move',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tictocmodel',
            name='winner',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
