# Generated by Django 4.2.6 on 2023-12-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictoc', '0003_alter_tictocmodel_action_alter_tictocmodel_move_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tictocmodel',
            name='board',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tictocmodel',
            name='player',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tictocmodel',
            name='terminal',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
