# Generated by Django 4.2.6 on 2023-12-03 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictoc', '0006_alter_tictocmodel_terminal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tictocmodel',
            name='move',
        ),
    ]
