# Generated by Django 4.2.6 on 2023-12-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictoc', '0007_remove_tictocmodel_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='tictocmodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
