# Generated by Django 4.2.6 on 2023-12-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictoc', '0008_tictocmodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tictocmodel',
            name='date',
        ),
        migrations.AddField(
            model_name='tictocmodel',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
