# Generated by Django 4.2.6 on 2023-10-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_crimescenereport_street_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='items/no_photo.jpg', upload_to='items'),
        ),
    ]
