# Generated by Django 4.2.6 on 2023-10-12 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_location_options_alter_person_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NpcReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Npc Reply',
                'verbose_name_plural': 'npc Replies',
            },
        ),
        migrations.RenameModel(
            old_name='Evidence',
            new_name='Clue',
        ),
        migrations.AlterModelOptions(
            name='airports',
            options={'verbose_name': 'Airport', 'verbose_name_plural': 'Airports'},
        ),
        migrations.AlterModelOptions(
            name='atmtransaction',
            options={'verbose_name': 'Atm Transaction', 'verbose_name_plural': 'Atm Transactions'},
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': 'Bank Account', 'verbose_name_plural': 'Bank Accounts'},
        ),
        migrations.AlterModelOptions(
            name='clue',
            options={'verbose_name': 'Clue', 'verbose_name_plural': 'Clues'},
        ),
        migrations.AlterModelOptions(
            name='crimescenereport',
            options={'verbose_name': 'Crime Scene Report', 'verbose_name_plural': 'Crime Scene Reports'},
        ),
        migrations.AlterModelOptions(
            name='flights',
            options={'verbose_name': 'Flight', 'verbose_name_plural': 'Flights'},
        ),
        migrations.AlterModelOptions(
            name='interviews',
            options={'verbose_name': 'Interview', 'verbose_name_plural': 'Interviews'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='messagebox',
            options={'verbose_name': 'Message Box', 'verbose_name_plural': 'Message Boxes'},
        ),
        migrations.AlterModelOptions(
            name='passengers',
            options={'verbose_name': 'Passenger', 'verbose_name_plural': 'Passengers'},
        ),
        migrations.AlterModelOptions(
            name='playerreply',
            options={'verbose_name': 'Player Reply', 'verbose_name_plural': 'Player Replies'},
        ),
        migrations.AlterModelOptions(
            name='securitylog',
            options={'verbose_name': 'Security Log', 'verbose_name_plural': 'Security Logs'},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'verbose_name': 'Street', 'verbose_name_plural': 'Streets'},
        ),
        migrations.RenameModel(
            old_name='player_reply',
            new_name='PlayerReply',
        ),
        migrations.DeleteModel(
            name='npc_reply',
        ),
        migrations.AddField(
            model_name='npcreply',
            name='PlayerReply_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playerreply'),
        ),
    ]
