# Generated by Django 4.2.6 on 2023-10-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.AddField(
            model_name='clue',
            name='description',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
