# Generated by Django 4.2.6 on 2023-10-19 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_item_description_clue_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clue',
            old_name='description',
            new_name='short_desc',
        ),
    ]
