# Generated by Django 4.2.6 on 2023-10-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_clue_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='type',
            field=models.CharField(choices=[('local', 'پرواز داخلی'), ('international', 'پرواز خارجی')], max_length=200),
        ),
    ]
